'use client';

import React, { useState } from 'react';
import { Card, CardContent, CardHeader, CardTitle, CardDescription } from '@/components/ui/card';
import { Button } from '@/components/ui/button';
import { Input } from '@/components/ui/input';
import { Copy, Check, Plus, Trash2, Settings2, Globe } from 'lucide-react';
import { Badge } from '@/components/ui/badge';
import { Select, SelectContent, SelectItem, SelectTrigger, SelectValue } from '@/components/ui/select';
import { Label } from '@/components/ui/label';

export default function RobotsGenerator() {
    const [sitemap, setSitemap] = useState('');
    const [userAgent, setUserAgent] = useState('*');
    const [crawlDelay, setCrawlDelay] = useState('none');
    const [disallowPaths, setDisallowPaths] = useState<string[]>(['/admin', '/private']);
    const [newPath, setNewPath] = useState('');
    const [copied, setCopied] = useState(false);

    const addPath = () => {
        if (newPath && !disallowPaths.includes(newPath)) {
            setDisallowPaths([...disallowPaths, newPath.startsWith('/') ? newPath : `/${newPath}`]);
            setNewPath('');
        }
    };

    const removePath = (index: number) => {
        setDisallowPaths(disallowPaths.filter((_, i) => i !== index));
    };

    const generateCode = () => {
        let code = `# Robots.txt generated by Assets Tools Hub\n`;
        code += `User-agent: ${userAgent}\n`;

        if (disallowPaths.length > 0) {
            disallowPaths.forEach(path => {
                code += `Disallow: ${path}\n`;
            });
        } else {
            code += `Allow: /\n`;
        }

        if (crawlDelay !== 'none') {
            code += `Crawl-delay: ${crawlDelay}\n`;
        }

        if (sitemap) {
            code += `\nSitemap: ${sitemap}`;
        }

        return code;
    };

    const copyToClipboard = () => {
        navigator.clipboard.writeText(generateCode());
        setCopied(true);
        setTimeout(() => setCopied(false), 2000);
    };

    return (
        <div className="max-w-4xl mx-auto space-y-8">
            <div className="grid gap-8 lg:grid-cols-5">
                {/* Configuration Sidebar */}
                <Card className="lg:col-span-2 border-primary/10 shadow-xl">
                    <CardHeader className="pb-4">
                        <CardTitle className="flex items-center gap-2">
                            <Settings2 className="h-5 w-5 text-primary" />
                            Configuration
                        </CardTitle>
                        <CardDescription>Customize your bot rules</CardDescription>
                    </CardHeader>
                    <CardContent className="space-y-6">
                        <div className="space-y-3">
                            <Label className="text-xs font-black uppercase tracking-widest opacity-70">User Agent</Label>
                            <Select onValueChange={setUserAgent} defaultValue="*">
                                <SelectTrigger className="h-11 rounded-xl">
                                    <SelectValue placeholder="All Bots (*)" />
                                </SelectTrigger>
                                <SelectContent>
                                    <SelectItem value="*">All Bots (*)</SelectItem>
                                    <SelectItem value="Googlebot">Googlebot</SelectItem>
                                    <SelectItem value="Bingbot">Bingbot</SelectItem>
                                    <SelectItem value="Baiduspider">Baiduspider</SelectItem>
                                    <SelectItem value="Slurp">Yahoo! Slurp</SelectItem>
                                    <SelectItem value="DuckDuckBot">DuckDuckBot</SelectItem>
                                </SelectContent>
                            </Select>
                        </div>

                        <div className="space-y-3">
                            <Label className="text-xs font-black uppercase tracking-widest opacity-70">Crawl Delay</Label>
                            <Select onValueChange={setCrawlDelay} defaultValue="none">
                                <SelectTrigger className="h-11 rounded-xl">
                                    <SelectValue placeholder="No Delay" />
                                </SelectTrigger>
                                <SelectContent>
                                    <SelectItem value="none">No Delay</SelectItem>
                                    <SelectItem value="1">1 Second</SelectItem>
                                    <SelectItem value="2">2 Seconds</SelectItem>
                                    <SelectItem value="5">5 Seconds</SelectItem>
                                    <SelectItem value="10">10 Seconds</SelectItem>
                                </SelectContent>
                            </Select>
                        </div>

                        <div className="space-y-3">
                            <Label className="text-xs font-black uppercase tracking-widest opacity-70">Sitemap URL</Label>
                            <div className="relative">
                                <Globe className="absolute left-3 top-3 h-5 w-5 text-muted-foreground" />
                                <Input
                                    placeholder="https://site.com/sitemap.xml"
                                    value={sitemap}
                                    onChange={(e) => setSitemap(e.target.value)}
                                    className="h-11 pl-10 rounded-xl"
                                />
                            </div>
                        </div>
                    </CardContent>
                </Card>

                {/* Main Content Areas */}
                <div className="lg:col-span-3 space-y-6">
                    <Card className="border-primary/10 shadow-lg">
                        <CardContent className="pt-6 space-y-4">
                            <Label className="text-xs font-black uppercase tracking-widest opacity-70">Disallowed Paths</Label>
                            <div className="flex gap-2">
                                <Input
                                    placeholder="e.g. /wp-admin"
                                    value={newPath}
                                    onChange={(e) => setNewPath(e.target.value)}
                                    onKeyDown={(e) => e.key === 'Enter' && addPath()}
                                    className="h-12 rounded-xl"
                                />
                                <Button onClick={addPath} size="icon" className="h-12 w-12 rounded-xl">
                                    <Plus className="h-5 w-5" />
                                </Button>
                            </div>

                            <div className="flex flex-wrap gap-2 pt-2">
                                {disallowPaths.map((path, i) => (
                                    <Badge key={i} variant="secondary" className="pl-3 pr-1 py-1.5 rounded-lg flex items-center gap-2 group hover:bg-destructive/10 hover:text-destructive transition-colors">
                                        <span className="font-mono">{path}</span>
                                        <button onClick={() => removePath(i)} className="p-0.5 rounded-md hover:bg-destructive/20">
                                            <Trash2 className="h-3 w-3" />
                                        </button>
                                    </Badge>
                                ))}
                                {disallowPaths.length === 0 && (
                                    <p className="text-sm text-muted-foreground italic py-2">No paths restricted. Bots will crawl everything.</p>
                                )}
                            </div>
                        </CardContent>
                    </Card>

                    <div className="relative group">
                        <div className="absolute inset-0 bg-primary/20 blur-[40px] opacity-0 group-hover:opacity-100 transition-opacity rounded-full -z-10" />
                        <Button
                            className="absolute top-4 right-4 z-20 h-10 px-4 rounded-xl shadow-lg border border-primary/20"
                            onClick={copyToClipboard}
                        >
                            {copied ? <Check className="h-4 w-4 mr-2" /> : <Copy className="h-4 w-4 mr-2" />}
                            {copied ? 'Copied!' : 'Copy Rules'}
                        </Button>
                        <div className="p-8 bg-zinc-950 text-green-400 rounded-3xl font-mono text-sm min-h-[250px] shadow-2xl relative overflow-hidden border border-white/5">
                            <div className="absolute top-0 left-0 w-full h-1 bg-gradient-to-r from-primary to-purple-500" />
                            <pre className="whitespace-pre-wrap leading-relaxed">
                                {generateCode()}
                            </pre>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    );
}
